# Generated by Django 5.1.2 on 2024-11-06 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activities_id', models.IntegerField()),
                ('Activities_Name', models.CharField(max_length=100)),
                ('Cost', models.IntegerField()),
                ('Type', models.CharField(max_length=100)),
                ('DateTime', models.DateTimeField()),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('iso_country', models.CharField(max_length=3)),
                ('iso_region', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=100)),
                ('iata_code', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hotel_id', models.IntegerField()),
                ('Hotel_name', models.CharField(max_length=200)),
                ('location_country', models.CharField(max_length=200)),
                ('location_city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depature_stop', models.CharField(max_length=100)),
                ('arrival_stop', models.CharField(max_length=100)),
                ('duration_formatted', models.CharField(max_length=10)),
                ('agencies', models.CharField(max_length=100)),
                ('agencies_url', models.TextField()),
                ('transport', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField()),
                ('Departure', models.DateTimeField(default=None)),
                ('Return', models.DateTimeField(default=None)),
                ('airport_city', models.ForeignKey(default='Hong Kong', on_delete=django.db.models.deletion.CASCADE, related_name='airport_city', to='RemoteDatabase.airport')),
                ('airport_iso_country', models.ForeignKey(default='HK', on_delete=django.db.models.deletion.CASCADE, related_name='airport_iso_country', to='RemoteDatabase.airport')),
                ('airport_name', models.ForeignKey(default='Hong Kong', on_delete=django.db.models.deletion.CASCADE, related_name='airport_name', to='RemoteDatabase.airport')),
                ('passenger_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='passenger_name', to='RemoteDatabase.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities', models.TextField()),
                ('locationList', models.TextField()),
                ('relatedServicePlatform', models.TextField()),
                ('packagesList', models.TextField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RemoteDatabase.flight_ticket')),
            ],
        ),
    ]
